config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :item_taxes
  resources :items do
    post :order , on: :collection
  end
  resources :item_categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :item_category
    has_many :item_taxes, :dependent => :destroy
    validates :name, :rate, presence: true

    def price_with_all_taxes
        org_price = self.rate
        add_value_tax = self.item_taxes.where(tax_type: "value").pluck(:tax).sum 
        arr_of_value_from_per = []
        self.item_taxes.where(tax_type: "percentage").each do |percentage|
            arr_of_value_from_per << (org_price.to_i * percentage.tax.to_i) /100
        end
        org_price.to_i + add_value_tax.to_i + arr_of_value_from_per.sum
    end
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
    has_many :items, :dependent => :destroy
    validates :name, presence: true
end

app/models/item_tax.rb
class ItemTax < ApplicationRecord
    belongs_to :item
    validates :tax_name, :tax_type, :tax, presence: true
    validate do |item_tax|
        item_tax.errors.add(:tax, "percentage should be < 100") if item_tax.tax_type == "percentage" && item_tax.tax.to_i > 100
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  before_action :set_item_category, only: %i[ show edit update destroy ]

  # GET /item_categories or /item_categories.json
  def index
    @item_categories = ItemCategory.all
  end

  # GET /item_categories/1 or /item_categories/1.json
  def show
  end

  # GET /item_categories/new
  def new
    @item_category = ItemCategory.new
  end

  # GET /item_categories/1/edit
  def edit
  end

  # POST /item_categories or /item_categories.json
  def create
    @item_category = ItemCategory.new(item_category_params)

    respond_to do |format|
      if @item_category.save
        format.html { redirect_to @item_category, notice: "Item category was successfully created." }
        format.json { render :show, status: :created, location: @item_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_categories/1 or /item_categories/1.json
  def update
    respond_to do |format|
      if @item_category.update(item_category_params)
        format.html { redirect_to @item_category, notice: "Item category was successfully updated." }
        format.json { render :show, status: :ok, location: @item_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_categories/1 or /item_categories/1.json
  def destroy
    @item_category.destroy
    respond_to do |format|
      format.html { redirect_to item_categories_url, notice: "Item category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_category
      @item_category = ItemCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_category_params
      params.require(:item_category).permit(:name)
    end
end

app/controllers/item_taxes_controller.rb
class ItemTaxesController < ApplicationController
  before_action :set_item_tax, only: %i[ show edit update destroy ]

  # GET /item_taxes or /item_taxes.json
  def index
    @item_taxes = ItemTax.all
  end

  # GET /item_taxes/1 or /item_taxes/1.json
  def show
  end

  # GET /item_taxes/new
  def new
    @item_tax = ItemTax.new
  end

  # GET /item_taxes/1/edit
  def edit
  end

  # POST /item_taxes or /item_taxes.json
  def create
    @item_tax = ItemTax.new(item_tax_params)

    respond_to do |format|
      if @item_tax.save
        format.html { redirect_to @item_tax, notice: "Item tax was successfully created." }
        format.json { render :show, status: :created, location: @item_tax }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item_tax.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_taxes/1 or /item_taxes/1.json
  def update
    respond_to do |format|
      if @item_tax.update(item_tax_params)
        format.html { redirect_to @item_tax, notice: "Item tax was successfully updated." }
        format.json { render :show, status: :ok, location: @item_tax }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item_tax.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_taxes/1 or /item_taxes/1.json
  def destroy
    @item_tax.destroy
    respond_to do |format|
      format.html { redirect_to item_taxes_url, notice: "Item tax was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_tax
      @item_tax = ItemTax.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_tax_params
      params.require(:item_tax).permit(:tax_name, :tax_type, :tax, :item_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  def order
    item_ids = params[:selected_items]
    @selected_items = Item.where(id: item_ids)
    @total_price = @selected_items.map { |string| string.price_with_all_taxes }.sum
  end

  # GET /items or /items.json
  def index
    @item_categories = ItemCategory.all
    @items = Item.includes(:item_tax).all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :rate, :item_category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_categories_helper.rb
module ItemCategoriesHelper
end

app/helpers/item_taxes_helper.rb
module ItemTaxesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/item_categories/_form.html.erb
<%= form_with(model: item_category, local: true) do |form| %>
  <% if item_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_category.errors.count, "error") %> prohibited this item_category from being saved:</h2>

      <ul>
        <% item_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item_categories/edit.html.erb
<h1>Editing Item Category</h1>

<%= render 'form', item_category: @item_category %>

<%= link_to 'Show', @item_category %> |
<%= link_to 'Back', item_categories_path %>

app/views/item_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_categories.each do |item_category| %>
      <tr>
        <td><%= item_category.name %></td>
        <td><%= link_to 'Show', item_category %></td>
        <td><%= link_to 'Edit', edit_item_category_path(item_category) %></td>
        <td><%= link_to 'Destroy', item_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Category', new_item_category_path %>

app/views/item_categories/new.html.erb
<h1>New Item Category</h1>

<%= render 'form', item_category: @item_category %>

<%= link_to 'Back', item_categories_path %>

app/views/item_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item_category.name %>
</p>

<%= link_to 'Edit', edit_item_category_path(@item_category) %> |
<%= link_to 'Back', item_categories_path %>

app/views/item_taxes/_form.html.erb
<%= form_with(model: item_tax, local: true) do |form| %>
  <% if item_tax.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_tax.errors.count, "error") %> prohibited this item_tax from being saved:</h2>

      <ul>
        <% item_tax.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tax_name %>
    <%= form.text_field :tax_name %>
  </div>

  <div class="field">
    <%= form.label :tax_type %>
    <%= form.text_field :tax_type %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.text_field :tax %>
  </div>
 
  <div class="field">
    <%= form.label :item %>
    <%= form.collection_select :item_id, Item.order(:name),:id,:name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item_taxes/edit.html.erb
<h1>Editing Item Tax</h1>

<%= render 'form', item_tax: @item_tax %>

<%= link_to 'Show', @item_tax %> |
<%= link_to 'Back', item_taxes_path %>

app/views/item_taxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Taxes</h1>

<table>
  <thead>
    <tr>
      <th>Tax name</th>
      <th>Tax type</th>
      <th>Tax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_taxes.each do |item_tax| %>
      <tr>
        <td><%= item_tax.tax_name %></td>
        <td><%= item_tax.tax_type %></td>
        <td><%= item_tax.tax %></td>
        <td><%= link_to 'Show', item_tax %></td>
        <td><%= link_to 'Edit', edit_item_tax_path(item_tax) %></td>
        <td><%= link_to 'Destroy', item_tax, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Tax', new_item_tax_path %>

app/views/item_taxes/new.html.erb
<h1>New Item Tax</h1>

<%= render 'form', item_tax: @item_tax %>

<%= link_to 'Back', item_taxes_path %>

app/views/item_taxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tax name:</strong>
  <%= @item_tax.tax_name %>
</p>

<p>
  <strong>Tax type:</strong>
  <%= @item_tax.tax_type %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @item_tax.tax %>
</p>

<%= link_to 'Edit', edit_item_tax_path(@item_tax) %> |
<%= link_to 'Back', item_taxes_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_field :rate %>
  </div>

  <div class="field">
    <%= form.label :item_category %>
    <%= form.collection_select :item_category_id, ItemCategory.order(:name),:id,:name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>
<%= form_tag order_items_path, method: :post, id: 'send-items-id' do  %>
  <% @item_categories.each do |item_category| %>
    <div> Category Name: <%= item_category.name %></div>
      <% if item_category.items.present? %>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Rate</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% item_category.items.each do |item| %>
              <tr>
                <td><%=check_box_tag 'selected_items[]', item.id%></td>

                <td><%= item.name %></td>
                <td><%= item.rate %></td>
                <td><%= link_to 'Show', item %></td>
                <td><%= link_to 'Edit', edit_item_path(item) %></td>
                <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        "No items Found"
      <% end%>
  <% end %>
  <br>
  <%= content_tag :button, :type => :submit, class: 'btn btn-success' do %>
    Submit
  <%end%>
<% end %> 
<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/order.html.erb
<p id="notice"><%= notice %></p>

<h1> Your selected Items with total price</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Orignal Rate</th>
      <th>Price with Tax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selected_items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.rate %></td>
        <td><%= item.price_with_all_taxes %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= "totle price: #{@total_price}" %>
<br>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @item.rate %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaxesApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Items', items_path %>

    <%= link_to 'Item categories', item_categories_path %>

    <%= link_to 'Item taxes', item_taxes_path %>

    <%= yield %>
  </body>
</html>